apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pr-preview-test-route-{{.Release.Name}}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: sadcloud
      namespace: default
  hostnames: 
    - {{ .Values.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: pr-preview-test-{{.Release.Name}}
          namespace: {{ .Release.Namespace }}
          port: 80
